# Generated by Django 4.2.1 on 2023-05-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('product_description', models.CharField(default='', max_length=1000)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('published_date', models.DateField(default='')),
                ('image', models.ImageField(default='', upload_to='store/images')),
            ],
        ),
    ]
